src/PruebaTecnica/Models/Triangulo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PruebaTecnica.Models
{
    public class Triangulo
    {
        // TODO...
    }
}

src/PruebaTecnica/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PruebaTecnica.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/PruebaTecnica/Controllers/MathController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PruebaTecnica.Controllers
{
    public class MathController : Controller
    {

        public ActionResult PerimetroCuadrado(double lado)
        {
            throw new NotImplementedException();
        }
    }
}

src/PruebaTecnica/Controllers/TrianguloController.cs
using PruebaTecnica.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PruebaTecnica.Controllers
{
    public class TrianguloController : Controller
    {

        [HttpGet]
        public ActionResult Area()
        {
            Triangulo triangulo = new Triangulo();
            return View(triangulo);
        }
	}
}

src/PruebaTecnica/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="panel-group">
    @Html.Partial("triangulo")
    @Html.Partial("cuadrado")
</div>

src/PruebaTecnica/Views/Home/cuadrado.cshtml
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" href="#cuadrado">Cuadrado</a>
        </h4>
    </div>
    <div id="cuadrado" class="panel-collapse in">
        <div class="panel-body">
            <p>
                <label>Lado:</label> <input type="number" id="ladoCuadrado" />
            </p>
            <p>
                <div id="btnAreaCuadrado" class="btn btn-primary">Area cuadrado (jQuery)</div>
                <span> = <span id="resAreaCuadrado">?</span> m<sup>2</sup>.</span>
            </p>
            <p>
                <div id="btnPerimetroCuadrado" class="btn btn-success">Perimetro cuadrado (jQueryAjax)</div>
                <span> = <span id="resPerimetroCuadrado">?</span> m.</span>
            </p>
        </div>
    </div>
</div>

<script type="text/javascript">

    Math.areaCuadrado = function (lado) {
        return lado * lado;
    };

    // Usando jQuery:
    //      Subscribirse a los eventos de los botones
    //      Resolver el area del cuadrado llamando a la funcion Math.areaCuadrado
    //      Resolver el perimetro llamando por Ajax a /Math/PermietroCuadrado?lado={valor}

</script>

src/PruebaTecnica/Views/Home/triangulo.cshtml
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" href="#triangulo">Triangulo</a>
        </h4>
    </div>
    <div id="triangulo" class="panel-collapse in">
        <div class="panel-body">
            @Html.ActionLink("Area triangulo (MVC)", "Area", "Triangulo", null, new { @class = "btn btn-primary", role = "button" })
        </div>
    </div>
</div>

src/PruebaTecnica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

</body>
</html>

src/PruebaTecnica/Views/Triangulo/Area.cshtml
@model PruebaTecnica.Models.Triangulo

<h2>Area triángulo</h2>

<form method="post">

    <!-- TODO.... -->

    <button type="submit">Calcular</button>
</form>

@if (IsPost)
{
    // TODO.....
}